### ISSUE TITLE
Problem with saving in MainActivity

### ISSUE THREAD

**Issue by Shmuser** [tilacyn/Saboteur#2]
In MainActivity in function onActivityResult: in case resultCode != RESULT_OK, nothing is being saved.

However in runtime this part of code is being executed when button switchPlayer from GameActivity has not been pressed, so next turn has not been started, before calling method onStop and returning to MainActivity. It is not quite right to accept controller this way, even though program works correctly

**Comment by tilacyn** [comment]
wow much inglish

**Comment by Shmuser** [comment]
I did screenshot and later i'll show it to Kuzya. Good work, guys.
